#!/bin/sh
name=$1
shift
select_by_name=".Reservations | map(.Instances) | map (select(.[0].Tags | map(select(.Key == \"Name\")) | select(.[0].Value==\"$name\"))) | .[0][0]"
get_instance_id=".InstanceId"
aws "$@" ec2 describe-instances --output json | jq "$select_by_name" | jq "$get_instance_id" | xargs echo # remove quotes
